[Logger]
  # 日志输出位置
  # 当为"console"时，输出到控制台
  # 否则，应提供文件路径，日志将输出到此文件中
  Filename="console"
  # 日志输出等级
  # 可选：debug < info < warn < error < dpanic < panic
  Level="debug"
  # 日志文件轮转
  MaxSize=1024 # 每MaxSize(MB)轮转
  MaxAge=1     # 每MaxAge(日)轮转
  MaxBackups=7 # 最多保留MaxBackups个日志文件

[[IPProvider]]
  Name="老夫"
  URL=""

[[IPProvider]]
  Name="亿牛云"
  URL=""

[[Server]]
  Bind=":9000"
  # 账号密码验证
  # 留空表示无需验证
  User="speng"
  Password="a123456"
  # IP提取渠道
  IPProviders=["老夫", "亿牛云"]
  # 最大并发处理量
  MaxConnections=3
  # 客户端连接总超时时间
  FlowTimeout=8000
  # 客户端连接读写超时时间
  TCPClientReadTimeout=2000
  TCPClientWriteTimeout=6000
  # 客户端连接等待被处理的超时时间
  # 此参数与MaxConnections、单个连接处理时间有关
  WaitForHandleTimeout=2000

[[Server]]
  Bind=":9001"
  # 账号密码验证
  # 留空表示无需验证
  User=""
  Password=""
  # IP提取渠道
  IPProviders=["老夫", "亿牛云"]
  # 最大并发处理量
  MaxConnections=3
  # 客户端连接总超时时间
  FlowTimeout=8000
  # 客户端连接读写超时时间
  TCPClientReadTimeout=2000
  TCPClientWriteTimeout=6000
  # 客户端连接等待被处理的超时时间
  # 此参数与MaxConnections、单个连接处理时间有关
  WaitForHandleTimeout=2000